version: "3.9"
services:
  api:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    ports:
      - "8099:8099"
    env_file:
      - ../../.env
    command: sh -c "sleep 4s && ./platform"

  migrate:
    build:
      context: ../../
      dockerfile: ./Dockerfile
    env_file:
      - ../../.env
    command: sh -c "sleep 4s && ./migrate"

networks:
  default:
    name: translation-network
    driver: bridge